train_data_path: /home/evgenii/work/itmo/coming_soon_ai_product_hack/item_064.csv
granularity: one_day
num_leaves: 31
learning_rate: 0.01
feature_fraction: 0.6  # Only use this for LightGBM
max_depth: 5
verbose: 1
early_stopping_rounds: 30  # Keep this and remove any early_stopping_round conflicts
nthread: -1
use_grid_search: true

grid_search:
  param_grid:
    num_leaves: [10, 20, 30]
    learning_rate: [0.001, 0.01, 0.1]
    feature_fraction: [0.6, 0.8, 1.0]
    max_depth: [5, 10, 15]
    n_estimators: [100, 500, 1000]
  cross_validation: 3
  scoring: 'neg_mean_squared_error'
  verbose: 1
  n_jobs: -1
