num_leaves: 40
learning_rate: 0.001
feature_fraction: 0.8
max_depth: 40
verbose: 0
num_boost_round: 1000
early_stopping_rounds: 500
nthread: -1

granularity: one_day

train_data_path: /home/evgenii/work/itmo/coming_soon_ai_product_hack/item_064.csv